- slug: digger
  name: Digger
  tagline: Friendly DNS lookup without the terminal
  github: tobagin/digger
  flathub: io.github.tobagin.digger
  resources:
    docs_url: "https://tobagin.github.io/digger/docs"
    wiki_url: "https://github.com/tobagin/digger/wiki"
    issues_url: "https://github.com/tobagin/digger/issues"
    discussions_url: "https://github.com/tobagin/digger/discussions"

- slug: karere
  name: Karere
  tagline: Modern chat client for Matrix
  github: tobagin/karere
  flathub: io.github.tobagin.karere
  resources:
    docs_url: "https://tobagin.github.io/karere/docs"
    issues_url: "https://github.com/tobagin/karere/issues"

- slug: keysmith
  name: KeySmith
  tagline: Point-and-click SSH key manager
  github: tobagin/keysmith
  flathub: io.github.tobagin.keysmith

- slug: secrets
  name: Secrets Manager
  tagline: Beautiful password safe for GNOME
  github: tobagin/secrets
  flathub: io.github.tobagin.secrets

- slug: sonar
  name: Sonar
  tagline: Local webhook inspector for developers
  github: tobagin/sonar
  flathub: io.github.tobagin.sonar

- slug: tempo
  name: Tempo
  tagline: A rock-solid metronome
  github: tobagin/tempo
  flathub: io.github.tobagin.tempo
